### ISSUE TITLE
[BUG] Game crashing when starting

### ISSUE THREAD

**Issue by Lordshaithis** [lukebemish/excavated_variants#174] opened 2023-10-02 08:48 UTC
### What went wrong?

The game starts to load and then once its finished loading all mods the game crashes instantly. Versions stated on curseforge page of mods etc.

### Platform

Forge

### Version

3.0.8

### Logs and Screenshots

[latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12781120/latest.log)

**Comment by lukebemish** [comment] 2023-10-02 14:20
Hmm. This log does not seem to include a crash. Could you provide a bit more information? How do you know that Excavated Variants is responsible?

**Comment by lukebemish** [comment] 2023-10-02 14:20
Additionally, could you include a debug.log file, as that will have more information?

**Comment by Lordshaithis** [comment] 2023-10-02 15:32
I know its excavated variants because its only when that mod is installed in the pack it does it, when i remove it from the pack its fine. Where in the minecraft folder do i find the debug.log?

**Comment by lukebemish** [comment] 2023-10-02 15:38
Should be in the `logs` folder though I believe CurseForge disables its creation by default - there should be a setting somewhere to turn it back on. Is there a pack you're adding Excavated Variants to to cause the crash? I can try to reproduce it locally with that.

**Comment by lukebemish** [comment] 2023-10-02 15:39
Is a crash report file generated? Even that would be useful. I'm just trying to figure out what's going on here as the latest.log file has very little information

**Comment by Lordshaithis** [comment] 2023-10-02 15:41
Im adding it to my own custom pack i made last night, i can send you the export of the pack if youd like? it will be missing excavated variants and dynamic asset gen.

Ive attached the pack here.
[The Beehive Modpack-1.0.zip](https://github.com/lukebemish/ExcavatedVariants/files/12784145/The.Beehive.Modpack-1.0.zip)

**Comment by lukebemish** [comment] 2023-10-02 15:42
Thank you. I'll see what I can find out

**Comment by Lordshaithis** [comment] 2023-10-02 15:43
Thankyou very much, its really frustrating not being able to get it to work because i love how this mod works and looks ingame.
 Makes it more immersive for sure!

**Comment by lukebemish** [comment] 2023-10-02 16:52
Okay, this isn't a crash but a very, *very* slow load. If you let it sit long enough it'll probably finish loading, though it may just decide that it's "not responding" and kill it. I've narrowed down what's going on to some logic in the Twilight Forest that... doesn't work well with some logic in DynAssetGen, to say the least. I'll look on mitigating it from my end, and try to contribute a fix to them as well if there's anything that can be done on that end to mitigate it.

**Comment by Lordshaithis** [comment] 2023-10-02 17:03
Okay thats a good start to know that, ill look forward to a possible fix.

**Comment by lukebemish** [comment] 2023-10-02 17:14
Alright, after some poking there's no easy way to fix this on my end - the proper solution is for Twilight Forest to change how they're doing stuff, and not re-open every single resource pack some 20 times. I've opened an issue with them - closing this for now with that in mind though if a way to fix it on my end is suggested I'll re-open it

**Closed as completed by lukebemish** 2023-10-02 17:14 UTC
Labels: bug, not us

**Comment by lukebemish** [comment] 2023-10-02 17:33
Looks like Twilight Forest has a fix already, so that'll hopefully be out soon

**Comment by Lordshaithis** [comment] 2023-10-02 18:43
Oh thats awesome
