### ISSUE TITLE
[BUG] Some ender ore only render in vanilla stone, not all (Texture Pack Issue, Sorry)

### ISSUE THREAD

**Issue by ardissaps** [lukebemish/excavated_variants#59] opened 2022-06-14 06:13 UTC
### What went wrong?

Only some, i also upload the one that works as comparison.

### Platform

Fabric

### Version

1.18.2

### Logs and Screenshots

This one from better nether (default provided by EV) :
![image](https://user-images.githubusercontent.com/82106625/173505303-92e998a9-97d1-48bf-9262-74562ff381e3.png)

This one from enderscape I added my self :
![image](https://user-images.githubusercontent.com/82106625/173505411-c142e625-e330-4db9-aa10-368fb49d9d84.png)

This one from enderscape I added my self but they work as comparison :
![image](https://user-images.githubusercontent.com/82106625/173505644-10150fea-4ba9-4e1d-9dda-2b3e061a9531.png)

My enderscape manually added json Nebulit works, but Shadows Quartz does not: 
![image](https://user-images.githubusercontent.com/82106625/173505841-4348a606-c88f-4f61-adfb-60e5cf7ceed5.png)

**Comment by ardissaps** [comment] 2022-06-14 06:17
So far I found that default EV provided that render vanilla only stone is from BetterEnd json : Ender ore, Thallasium Ore.

While manually added is only Shadow Quartz does not work. Nebulite works.

These one as example for Violecite one of the stone provided by betterend that contain 3 of that ore mentioned :
![point](https://user-images.githubusercontent.com/82106625/173508783-bbd59789-89d5-45bf-8fdf-4d755a43bc22.jpg)

**Comment by ardissaps** [comment] 2022-06-14 08:35
I disabled texture pack and fixed, is there work around like yesterday? should I increase the texture count? as it is not purple like yesterday, only forced to use endstone.

No hurry sir, take your time. While waiting I am probably delete stay true ender stone texture. :)

**Comment by lukebemish** [comment] 2022-06-14 11:56
Please provide the configs for the ores in question.

**Comment by ardissaps** [comment] 2022-06-14 13:05
{
  "mod_id": "betterend",
  "provided_stones": [
    {
      "block_id": "betterend:brimstone",
      "types": [
        "end"
      ],
      "id": "betterend_brimstone",
      "en_name": "Brimstone"
    },
    {
      "block_id": "betterend:umbralith",
      "types": [
        "end"
      ],
      "id": "betterend_umbralith",
      "en_name": "Umbralith"
    },
    {
      "block_id": "betterend:azure_jadestone",
      "types": [
        "end"
      ],
      "id": "betterend_azure_jadestone",
      "en_name": "Azure Jadestone"
    },
    {
      "block_id": "betterend:sandy_jadestone",
      "types": [
        "end"
      ],
      "id": "betterend_sandy_jadestone",
      "en_name": "Sandy Jadestone"
    },
    {
      "block_id": "betterend:virid_jadestone",
      "types": [
        "end"
      ],
      "id": "betterend_virid_jadestone",
      "en_name": "Virid Jadestone"
    },
    {
      "block_id": "betterend:sulphuric_rock",
      "types": [
        "end"
      ],
      "id": "betterend_sulphuric_rock",
      "en_name": "Sulfuric Rock"
    },
    {
      "block_id": "betterend:violecite",
      "types": [
        "end"
      ],
      "id": "betterend_violecite",
      "en_name": "Violecite"
    },
    {
      "block_id": "betterend:flavolite",
      "types": [
        "end"
      ],
      "id": "betterend_flavolite",
      "en_name": "Flavolite"
    }
  ],
  "provided_ores": [
    {
      "block_id": [
        "betterend:thallasium_ore"
      ],
      "en_name": "Thallasium Ore",
      "types": [
        "end"
      ],
      "texture_count": 5,
      "id": "thallasium_ore",
      "stone": [
        "end_stone"
      ]
    },
    {
      "block_id": [
        "betterend:amber_ore"
      ],
      "en_name": "Amber Ore",
      "types": [
        "end"
      ],
      "texture_count": 5,
      "id": "amber_ore",
      "stone": [
        "end_stone"
      ]
    },
    {
      "block_id": [
        "betterend:ender_ore"
      ],
      "en_name": "Ender Ore",
      "types": [
        "end"
      ],
      "texture_count": 5,
      "id": "ender_ore",
      "stone": [
        "end_stone"
      ]
    }
  ]
}

**Comment by ardissaps** [comment] 2022-06-14 13:06
BetterEnd :
https://pastebin.com/c2XEpVDj

Enderscape : 
https://pastebin.com/FN8CAeZL

**Comment by lukebemish** [comment] 2022-06-14 13:14
I have an idea what the issue is; I'll see how much I'm able to do about it.

**Comment by ardissaps** [comment] 2022-06-14 15:28
Okay thank you very much.

**Comment by lukebemish** [comment] 2022-06-14 23:03
Just to confirm, the issue does not occur with the texture pack off?

**Comment by ardissaps** [comment] 2022-06-15 01:26
> Just to confirm, the issue does not occur with the texture pack off?

Yes, no problem with default texture pack, maybe problem from the StauTrue? RN I edited their zip files and remove end stone texture and problem fixed, not yet trying other texturepack.

**Comment by ardissaps** [comment] 2022-06-15 03:06
It is now happening with Palladium Ores, vanilla texture, all the stone use netherrack

**Comment by lukebemish** [comment] 2022-06-16 16:19
The issue with Palladium is a known bug, and an issue with the default configs. The ore is not configured to use netherrack by default, but by stone. This is fixed in the 1.19 version, and will be fixed in 1.18 as well if a new version is released.

**Comment by lukebemish** [comment] 2022-06-16 16:23
The issue with the Stay True end stone textures appears to be this: the end stone texture from that resource pack appears to be far enough off from the vanilla end stone texture that the background can no longer be extracted from the ore textures. There is unfortunately no way to fix this; though EV works with many resource packs, it works best, and reliably, when the resource pack affects *all* the textures in question. I'm going to close this, but I'll leave it unlocked in case there's another cause for this.

**Comment by lukebemish** [comment] 2022-06-16 16:24
(If you'd provide a log, I may be able to rule out a couple of other potential causes for the issue, though I suspect my guess is correct here)

**Closed as not planned by lukebemish** 2022-06-16 16:23 UTC
Labels: bug

**Comment by ardissaps** [comment] 2022-06-16 22:28
I see, I decide to edit zip and remove stay true end stone file as they are not significant difference with vanilla, thank you for the time. I see so Palladium is known issue and it is fine right now as it is only 1 ore set and not a big deal, so no need to be hurry. Take your time, thanks for the great mods and helps! I'll report further if found problem.

**Comment by lukebemish** [comment] 2022-06-16 22:31
Palladium has already been fixed, but development on 1.18 has mostly stopped and I will likely only release one more version with a variety of bugfixes. You can fix it yourself by changing the config.

**Comment by ardissaps** [comment] 2022-06-16 23:36
> Palladium has already been fixed, but development on 1.18 has mostly stopped and I will likely only release one more version with a variety of bugfixes. You can fix it yourself by changing the config.

Yes, thank you very much for the assistance. I switching to 1.19 too, only need to wait some necessary mods to update while playing 1.18.
