### ISSUE TITLE
[BUG] EV ores don't drop XP

### ISSUE THREAD

**Issue by Jeuvke** [lukebemish/excavated_variants#77] opened 2022-07-06 18:32 UTC
### What went wrong?

Things like redstone ore or diamond ore in other blocks don't drop any XP when mined.

### Platform

Forge

### Version

0.6.2

**Comment by lukebemish** [comment] 2022-07-06 18:33
Provide your logs, please. I don't *think* forge made any breaking changes on their end, but logs would help narrow down the cause.

**Comment by Jeuvke** [comment] 2022-07-06 18:36
Server logs or client logs?

**Comment by lukebemish** [comment] 2022-07-06 18:38
Ah, this is on a dedicated server; that's the sort of important information you need to include. Server logs, please; possibly client logs down the road, but I doubt they're necessary here.

**Comment by Jeuvke** [comment] 2022-07-06 18:57
It's pretty big because of log spam, but here it is:
https://gist.github.com/Jeuvke/a27d43aca7f6b104fc311622c91750a3

**Comment by lukebemish** [comment] 2022-07-06 18:59
Can you fix your configs, and try running it again?

**Comment by Jeuvke** [comment] 2022-07-06 19:03
This is the default config that comes with the bliss mod pack, I guess I'll report it there.

**Comment by lukebemish** [comment] 2022-07-06 19:04
Oh yeah, that modpack has known issues in its EV configs. Not sure why they haven't fixed it yet as I yell at them in the log. Regardless, I'm not sure that's the cause of this issue; I'll look into it a bit more and see what I can figure out.

**Comment by lukebemish** [comment] 2022-07-06 19:06
Can confirm that this is a bug with just EV and vanilla on forge 1.18.2. Not sure what's going on; I'll take a look at it before the final 1.18.2 release.

**Comment by Vazkii** [comment] 2022-07-06 19:58
> Oh yeah, that modpack has known issues in its EV configs. Not sure why they haven't fixed it yet as I yell at them in the log. Regardless, I'm not sure that's the cause of this issue; I'll look into it a bit more and see what I can figure out.

Because your error message is entirely undescriptive and ends up printing in the middle of a bunch of known acceptable errors in mixins. It doesn't even specify which mod is causing it.

![image](https://user-images.githubusercontent.com/1794735/177632522-15b1d076-4397-4ffc-a6b0-c5558ba39aa5.png)

**Comment by lukebemish** [comment] 2022-07-06 19:59
It *definitely* says which mod is causing it...
![image](https://user-images.githubusercontent.com/53243629/177632754-b41b0bb2-480c-416e-86c1-a1e2c5e9d783.png)

**Comment by lukebemish** [comment] 2022-07-06 19:59
And it says "if we loaded this config, it would crash the game". Which I thought would imply that said config should be fixed.

**Comment by lukebemish** [comment] 2022-07-06 20:01
Regardless, the lack of XP drops is a separate issue, unrelated to the bad config in the modpack. It should be fixed in the next 1.18.2 release, once I finish tracking down the exact cause.

**Comment by Vazkii** [comment] 2022-07-06 20:05
Weird it doesn't in mine, we must have a different config for logging then.

**Comment by lukebemish** [comment] 2022-07-06 20:06
Logging menus often cut out data; it is best never to rely on them, and look at the raw log instead. From the fact that your logging menu cut this out, you're likely missing a ton of other information about what things are logging which messages.

**Comment by Vazkii** [comment] 2022-07-06 20:06
My brother in christ this is the latest.log file

**Comment by Hubry** [comment] 2022-07-06 20:07
I think Curseforge's launch process uses a weird custom logging config, if this was launched through that. They also make the debug.log not appear by default for some weird reason.

**Comment by lukebemish** [comment] 2022-07-06 20:09
Ah, that would make sense. Unfortunately, there's nothing mod authors can do about that; the system most of us use to mark what thing is logging the messages is pretty standardized, and if CF is cutting out that information that seems like a major issue.

**Comment by lukebemish** [comment] 2022-07-08 22:00
Assuming I didn't break anything else, should be fixed in new release

**Closed as completed** 2022-07-08 21:59 UTC
Labels: bug
