### ISSUE TITLE
[BUG] Issue with the texture

### ISSUE THREAD

**Issue by fagter** [lukebemish/excavated_variants#147] opened 2023-08-03 09:07 UTC
### What went wrong?

i downloaded some texture pack and now the variant are broken so i go to my texture pack menu and see that the texture pack for the variant is all down but it's a pack that i can't move so i shearch how to make it movable but i didn't found

### Platform

Quilt

### Version

1.20.1-3.0.5

### Logs and Screenshots

![image](https://github.com/lukebemish/ExcavatedVariants/assets/53382193/5f3058f1-e342-48be-9e99-5f7dc3b3ace4)

**Comment by lukebemish** [comment] 2023-08-03 12:19
Can you share a link to the texture pack that caused this issue?

**Comment by lukebemish** [comment] 2023-08-03 12:21
Additionally, please share your log. I cannot do anything without that

**Comment by fagter** [comment] 2023-08-04 07:10
i used a lot of texture pack but the one that modify all the texture is this one 

https://www.minecraft-france.fr/resource-pack-bare-bones/

and u want all of my log or just the error

**Comment by lukebemish** [comment] 2023-08-04 14:08
The whole log please.

**Comment by lukebemish** [comment] 2023-08-20 21:39
Just following up as it's been a few weeks; I'm struggling to reproduce this on my end, and the log includes important information for debugging this. Could you share your log?

**Comment by lukebemish** [comment] 2023-10-02 14:21
Closing this for now, as I can do nothing about this without a log (and because many of these sorts of issues will disappear in 1.20.2 anyways)

**Closed as completed by lukebemish** 2023-10-02 14:21 UTC
Labels: bug
