### ISSUE TITLE
Excavated Variants doesn't seem to load

### ISSUE THREAD

**Issue by PinkLasagna03** [lukebemish/excavated_variants#137] opened 2023-07-16 16:59 UTC
### What went wrong?

I've installed the mod along with the rest of a custom modpack, except it doesn't seem to be loaded into the game. 

### Platform

Forge

### Version

1.20.1

### Logs and Screenshots

[latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12064615/latest.log)

**Comment by PinkLasagna03** [comment] 2023-07-16 17:04
It doesn't seem to work either with all the other mods deleted
[latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12064622/latest.log)

**Comment by lukebemish** [comment] 2023-07-16 17:05
Hmm. Could you try downgrading dynamic asset generator to 4.1.0 and seeing if that works?

**Comment by lukebemish** [comment] 2023-07-16 17:08
If that doesn't change anything, then this appears like it might be some sort of strange behavior caused by an unexpected interaction with Xaero's World Map. I should be able to fix it on my end now that I know about it, at least as long as that mod isn't doing anything strange. However, if you could check how 4.1.0 works that would be great

**Comment by PinkLasagna03** [comment] 2023-07-16 17:30
> If that doesn't change anything, then this appears like it might be some sort of strange behavior caused by an unexpected interaction with Xaero's World Map. I should be able to fix it on my end now that I know about it, at least as long as that mod isn't doing anything strange. However, if you could check how 4.1.0 works that would be great

I tried, didn't work in my modpack. Tried it just with those two too in a seperate profile; didn't work either.

**Comment by lukebemish** [comment] 2023-07-16 17:43
Just which two? Excavated Variants and DynAssetGen? If you have a log with this error and just those two mods, please provide it here

**Comment by PinkLasagna03** [comment] 2023-07-16 17:58
> Just which two? Excavated Variants and DynAssetGen? If you have a log with this error and just those two mods, please provide it here

Yess, those two. 
[latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12064724/latest.log)

**Comment by lukebemish** [comment] 2023-07-16 17:59
That does not seem to be an error log? Does it crash? What exactly goes wrong?

**Comment by PinkLasagna03** [comment] 2023-07-16 18:13
> That does not seem to be an error log? Does it crash? What exactly goes wrong?

The game doesn't crash and there doesn't seem any error logs. The problem is with the mod installed I don't see any of the excavated variants in the creative menu, nor doesn't they seem to spawn in the world.

**Comment by lukebemish** [comment] 2023-07-16 18:24
That would be an entirely separate issue to this one then. Can you provide the debug.log?

**Comment by lukebemish** [comment] 2023-07-16 18:28
Locally, they are not showing up in the creative tab (which I will fix shortly) but are showing up just fine in the world; you just have to search a bit, because they only pop up where a stone vein and ore vein intersect

**Comment by lukebemish** [comment] 2023-07-16 18:34
Alright, the issue popping up with Xaero's World Map should be fixed in DynAssetGen 4.1.3

**Comment by PinkLasagna03** [comment] 2023-07-16 18:35
> Locally, they are not showing up in the creative tab (which I will fix shortly) but are showing up just fine in the world; you just have to search a bit, because they only pop up where a stone vein and ore vein intersect

Omg really? I was soo confused cause in the past versions they were showing up. Thanks anyways. I'll let you know if the issue still appears

**Comment by lukebemish** [comment] 2023-07-16 18:38
The creative tab being missing should be fixed in the next version of Excavated Variants, which will be released in a few minutes. Closing for now; please comment if either issue pops up again

**Closed as completed by lukebemish** 2023-07-16 18:38 UTC
Labels: bug
