### ISSUE TITLE
[BUG] Issue with Textures

### ISSUE THREAD

**Issue by TheButterbrotMan** [lukebemish/excavated_variants#33] opened 2022-04-22 01:42 UTC
### What went wrong?

Most byg textures are broken

### Platform

Fabric

### Version

0.5.1

### Logs and Screenshots

![image](https://user-images.githubusercontent.com/64548098/164579976-46332680-7a82-49b4-ac99-0c64f6d83668.png)

**Comment by lukebemish** [comment] 2022-04-22 02:04
Log?

**Comment by TheButterbrotMan** [comment] 2022-04-22 02:23
https://bytebin.lucko.me/8mz9M5HLaI

**Comment by lukebemish** [comment] 2022-04-22 02:52
Huh. That's a *weird* error, but I think I know the cause. Will be fixed soon.

**Comment by lukebemish** [comment] 2022-04-22 04:03
Have you reset your configs, and your DynAssetGen cache if you have that on?

**Comment by lukebemish** [comment] 2022-04-22 21:13
Currently, I cannot reproduce this on my end. It looks like what you might see if your cache hadn't been reset, and you were using that. Please try that, or let me know if you're not using caching.

**Comment by lukebemish** [comment] 2022-04-23 03:08
Huh, I've managed to reproduce a similar issue but for me it's only the textures, not the models, that fail to generate. I will investigate it further.

**Comment by lukebemish** [comment] 2022-04-23 03:40
Should be fixed as of newest commits, if it was the same issue I was having. Either way, try removing the cache.

**Closed as completed by lukebemish** 2022-04-23 03:40 UTC
Labels: bug
