### ISSUE TITLE
[BUG] Diamond variants texture bug

### ISSUE THREAD

**Issue by brnbrd** [lukebemish/excavated_variants#96] opened 2022-10-05 14:58 UTC
### What went wrong?

All diamond variants have a horribly stretched texture

### Platform

Forge

### Version

1.0.3

### Logs and Screenshots

![2022-10-05_07 57 40](https://user-images.githubusercontent.com/18539948/194093052-5fc45a1a-37d4-4f05-8a48-bf8d4c2f8b1f.png)

**Comment by lukebemish** [comment] 2022-10-05 15:22
Duplicate of lukebemish/dynamic_asset_generator#21. A temporary fix is to disable whatever resource pack is adding animated textures; will be fixed in the next DynAssetGen version

**Closed as completed** 2022-10-05 15:22 UTC
Labels: bug
